//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDMVCDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public long RefID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public string Section { get; set; }
        public string Branch { get; set; }
        public string Address { get; set; }
        public Nullable<int> CellNumber { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
    }
}
