//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDMVCDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public int gkey { get; set; }
        public string Username { get; set; }
        
        public string Password { get; set; }
        public string EncryptedPassword { get; set; }
        public string Fullname { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }

        public List<UserAccount> userlist { get; set; }
    }
}
